### ISSUE TITLE
VMWare-iso builder has no 'format' property

### ISSUE THREAD

**Issue by hongjoonchew** [mayn/packerlicious#103]
### Version
Currently using packerlicious 0.6.0 (latest as of)

### Expected behavior
Tried building VMWare-iso json file with 'format' prop.

### Actual behavior
'format' prop is not found inside the builder.py VMWare-iso method.

### Steps to reproduce
`builder.VMwareIso(format = 'ovf')`
 This should allow a build, but instead it returns an error because 'format' is not a prop. I made a personal hotfix in the builder.py to allow format.

**Comment by mayn** [comment]
thanks @hongjoonchew. released v0.6.1 to pypi w/ your change. 
Let me know if you still have an issue.
