### ISSUE TITLE
python3 add compatibility

### ISSUE THREAD

**Issue by mayn** [mayn/packerlicious#11]
fix python 3 compatibility, maintain python 2 compatibility

**Comment by blazejkw** [comment]
Hi,

Can I try to fix this isue ? I'd like to try with some automatic tool 
https://docs.python.org/2/library/2to3.html

are You ok with that ?
Regards

**Comment by blazejkw** [comment]
or If You would like to be ok both with python 2 and python 3 at the same time I would need to introduce smth like:

https://github.com/WildCard65/ambuild/commit/499519246654cccddbcd6883a19eb6a387fffbe1

**Comment by mayn** [comment]
@blazejkw  go for it!
I'd like to keep both python2/3 compatibility vs dropping python 2 support.

I started doing this a little while ago via futures, ran into an issue with the validation failing due to class mismatch between the future injected basestr class and `str` defined. 
Haven't had time to debug.

I pushed up my branch so you can see (https://github.com/mayn/packerlicious/tree/python3-future)
I haven't ran it for a while (apologize in advance if you have trouble running, let me know).

open to other ideas.
