### ISSUE TITLE
GoogleCompute Builder does not work with "source_image_family" key

### ISSUE THREAD

**Issue by adarobin** [mayn/packerlicious#111]
### packerlicious version
0.8.0

### Expected behavior
I expected to be able to use the `source_image_family` option in place of the `source_image` option.  Per the documentation, at least one or the other is required.

### Actual behavior
`ValueError: Resource source_image required in type googlecompute`

### Steps to reproduce
```
template = Template()
gcp_builder = builder.GoogleCompute(
account_file = "{{user `gcp_account_file`}}",
project_id = "{{user `gcp_project_id`}}",
zone = "{{user `gcp_zone`}}",
source_image_family = "ubuntu-1804-lts",
disk_size = 10,
disk_type = "pd-ssd",
machine_type = "n1-standard-2",
image_name = "test-ubuntu-1804-bionic-v{{isotime \"20060102\"}}",
image_family = "test-ubuntu-1804-lts",
communicator = "ssh"
)
template.add_builder(gcp_builder)
print template.to_json()
```

**Comment by mayn** [comment]
thanks @adarobin for reporting, please update to v0.8.1 and report any additional issues

**Comment by adarobin** [comment]
@mayn This seems to be working now, thanks!
