### ISSUE TITLE
shutdown_behavior

### ISSUE THREAD

**Issue by levisbakalinsky** [mayn/packerlicious#122]
### packerlicious version

Packerlicious: 1.0.1
Packer: 1.3.0

### Expected behavior

shutdown_behavior="terminate" should have passed validation and not thrown an error. Packer expects "terminate" not ["terminate"]

### Actual behavior

shutdown_behavior="terminate",
TypeError: <class 'packerlicious.builder.AmazonEbs'>: None.shutdown_behavior is <type 'str'>, expected [<type 'str'>]

### Steps to reproduce

Set shutdown_behavior="terminate",

**Comment by levisbakalinsky** [comment]
See this page for formatting. Looked through packer change log, but haven't found if they recently changed the format.

https://www.packer.io/docs/builders/amazon-ebs.html#shutdown_behavior

**Comment by mayn** [comment]
@levisbakalinsky v1.0.2 was released w/ this change. Thanks!
