### ISSUE TITLE
builder/AmazonChroot add prop from_scratch

### ISSUE THREAD

**Issue by mayn** [mayn/packerlicious#126]
packer v1.3.1 feature sync
see: https://www.packer.io/docs/builders/amazon-chroot.html#from_scratch

add attribute to https://github.com/mayn/packerlicious/blob/master/src/packerlicious/builder.py#L260

**Comment by isaacm** [comment]
The `from_scratch` attribute is already in the class `AmazonChroot` what else is missing to complete this ticket? validation of the additional required attributes when `from_scratch` is set to True?

```
If true, source_ami is no longer used and the following options become required: ami_virtualization_type, pre_mount_commands and root_volume_size.
```

**Comment by mayn** [comment]
@isaacm good catch, this is oversite on my part. 
feel free to move onto another tix. The additional conditional validation would be a welcomed addition though.
