### ISSUE TITLE
Docker run_command validation is incorrect, should be list of strings

### ISSUE THREAD

**Issue by Tegereo** [mayn/packerlicious#133]
https://github.com/mayn/packerlicious/blob/739a415c1fd74252e7d00e3574532c01322b8f95/src/packerlicious/builder.py#L770

Docker `run_command` should be a list of strings, not a string. See https://www.packer.io/docs/builders/docker.html#run_command

I'll throw a pull request together if I get the time, but wanted to at least document.

**Comment by PacketPerception** [comment]
@gnewson first one to a pull request wins! (It wont be me, i have no free time anymore)

**Comment by mayn** [comment]
@PacketPerception v1.0.2 was released w/ this change. Thanks!
