### ISSUE TITLE
add support for builders/amazon

### ISSUE THREAD

**Issue by mayn** [mayn/packerlicious#16]
[https://www.packer.io/docs/builders/amazon.html](https://www.packer.io/docs/builders/amazon.html)

* amazon-chroot
* amazon-ebssurrogate
* amazon-ebsvolume

**Comment by blazejkw** [comment]
Hi Mayn,

I'd like to help You with this issue

Regards

**Comment by mayn** [comment]
Hi @blazejkw , I look forward to your PR(s). Thanks for your interest

**Comment by blazejkw** [comment]
Hi,
sorry for doing such a mess :)
