### ISSUE TITLE
Custom Data Parameter for Manifest Post-Processor

### ISSUE THREAD

**Issue by levisbakalinsky** [mayn/packerlicious#169]
### packerlicious version

1.3.1

### Expected behavior

Add custom_data parameter for Manifest Post-Processor
https://www.packer.io/docs/post-processors/manifest.html#custom_data

Would like to be able to do something like this.
```
template.add_post_processor(
    post_processor.Manifest(
        output='/tmp/file.json',
        strip_path=False,
        custom_data={ "my_custom_data": "example"}
    )
)
```

**Comment by mayn** [comment]
thanks @levisbakalinsky , released  v1.4.0 w/ fix
