### ISSUE TITLE
add examples (multiple welcome)

### ISSUE THREAD

**Issue by mayn** [mayn/packerlicious#17]
add additional examples that are interesting/ realistic to packerlicious to `examples` and resulting json to `tests/examples_output` that highlight different use cases

here are some additional examples, that packer is working on (https://github.com/hashicorp/packer/pull/5427)

**Comment by nrebhun** [comment]
I'm going to give this a go! ☕️

**Comment by mayn** [comment]
@nrebhun hally hacking! (Please leave ticket open for others as well)
