### ISSUE TITLE
Support multiple named parallel builds of the same type

### ISSUE THREAD

**Issue by canstudios-simonm** [mayn/packerlicious#171]
### packerlicious version

1.4.0

### Expected behavior

Used packerlicious to build a template and then used packer.py to run it.
Expected to run multiple parallel AmazonEbs builds, differentiated by their name (not type)

### Actual behavior

Traceback (most recent call last):
  File "./updates.py", line 33, in <module>
    "BuildTime": current_date
  File "/usr/local/lib/python3.4/dist-packages/packerlicious/builder.py", line 81, in __init__
    super(PackerBuilder, self).__init__(title, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/packerlicious/builder.py", line 75, in __init__
    super(PackerCommunicator, self).__init__(title, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/thirdparty/troposphere/__init__.py", line 97, in __init__
    self.__setattr__(k, v)
  File "/usr/local/lib/python3.4/dist-packages/thirdparty/troposphere/__init__.py", line 186, in __setattr__
    (type_name, name))
AttributeError: amazon-ebs object does not support attribute name

### Steps to reproduce
Add a name property in the AmazonEbs builder template. e.g,
template.add_builder(
    builder.AmazonEbs(
        name="MyBuilder1",
        etc...
template.add_builder(
    builder.AmazonEbs(
        name="MyBuilder2",
        etc...

See above.

<FIX>
Add a new prop value for 'name' in packerlicious/builder.py in class AmazonEbs(PackerBuilder):
e.g, 
    props = {
        'name' : (str, False),
        etc...

**Comment by canstudios-simonm** [comment]
Looks like it took it off the end but I tried the following and it worked:

edit:
packerlicious/builder.py
class AmazonEbs(PackerBuilder)

add in a new prop for name e.g,
    props = {
        'name': (str, False),
        etc...

**Comment by mayn** [comment]
reference:
    named builds https://www.packer.io/docs/templates/builders.html#named-builds

**Comment by mayn** [comment]
thanks for reporting @canstudios-simonm , [v1.4.1](https://github.com/mayn/packerlicious/releases/tag/v1.4.1) was released with a fix.

**Comment by canstudios-simonm** [comment]
Just ran a couple of tests and can confirm that this has fixed the problem. Thanks :)
