### ISSUE TITLE
python wrapper for packer binary

### ISSUE THREAD

**Issue by mayn** [mayn/packerlicious#21]
packerlicious is limited to generating json template. This is good.
It would be better if this could be feed directly to the packer binary for processing.

challenge:
 create packer.py that can be fed a  packerlicious template for things like
- template validation
- template execution

basically a python interface to these commands https://www.packer.io/docs/commands/index.html

**should:**
- check if the binary is available, fail with an error saying that it was not found otherwise
- capture output from command and make available in a pythonic format

**may:**
- work when ran on linux + windows (

**Comment by Hrily** [comment]
I would like to take this up.
Any suggestions on how to start...

**Comment by mayn** [comment]
hi @Hrily , thanks for your interest.
I updated the requirements a bit to give you a high level idea of what to do.

in its simplest form:
- check for packer library
- call packer library
- capture response of library and return to the caller

hopefully this helps, if not lets continue the discussion.

looking forward to your PR!

**Comment by Hrily** [comment]
Yeah
I got the idea, will start working on it...

Do you have any test cases that I should/must pass, for checking correctness?

**Comment by mayn** [comment]
Thanks @Hrily. 
Ended up Doing alternate implementation as separate repository https://github.com/mayn/packer.py
