### ISSUE TITLE
README.rst remove leading ellipsis from python example 

### ISSUE THREAD

**Issue by mayn** [mayn/packerlicious#28]
remove leading ellipsis shown python console example (https://github.com/mayn/packerlicious#examples) , replace with leading spaces.

rational:
you can't just copy and paste the  example and try for yourself. You must first remove leading ellipsis, this is annoying.

**Comment by KshitijKarthick** [comment]
I'll take this issue up for resolving

**Comment by VijayGomathi** [comment]
@KshitijKarthick sorry I have been working on this earlier than you. Forgot to mention here.

**Comment by mayn** [comment]
Let me know what you guys decide

**Comment by KshitijKarthick** [comment]
@mayn Well first thing first, nicely handled :smile: 
Everyone should feel welcomed whatever little or big be their contribution.

I think splitting will rather make it more tedious then easily solving the issue.
You can go ahead with @VijayGomathi Pull Request, I have no issues with the same.

@VijayGomathi Hope you comment on the issue next time, will save the effort of whatever individuals put into making a contribution

**Comment by mayn** [comment]
@KshitijKarthick will do. maybe you can help me with this instead https://github.com/mayn/packerlicious/issues/31
