### ISSUE TITLE
tests generated from examples are not failing

### ISSUE THREAD

**Issue by mayn** [mayn/packerlicious#44]
### Expected behavior
the [examples](https://github.com/mayn/packerlicious/tree/master/examples) folder is also used to auto-generate unittests during pytest invocation.
These tests compare their json generation to their respective json stored in [examples_output](https://github.com/mayn/packerlicious/tree/master/tests/examples_output)

If either the python or the json changes, the test should fail (modifying json output, run tox)
most of this is controlled by the logic in 
- https://github.com/mayn/packerlicious/blob/master/tests/conftest.py
- https://github.com/mayn/packerlicious/blob/master/tests/packerlicious/test_examples.py

Open to achieving same expected behavior in a simpler fashion and ditching this complexity)

### Actual behavior
tests do not fail when there is a discrepancy between the python example and the json expected results

### Steps to reproduce
- change "t2.micro" to "t2.bad" in https://github.com/mayn/packerlicious/blob/master/tests/examples_output/getting_started_example.template#L6 
- run `tox -e py27` or equivilent
- pytest results report as pass (this is incorrect)

**Comment by bnmalcabis** [comment]
Hi @mayn, can I work on this ticket?

**Comment by mayn** [comment]
@bnmalcabis go for it! thanks for you interest.
