### ISSUE TITLE
appveyor - python 26 started failing

### ISSUE THREAD

**Issue by mayn** [mayn/packerlicious#52]
python 2.6 environment started failing on appveyor in the last 24 hours.
It continues to pass on python 2.6 travis ci.

look into why and open a PR that fixes it.
last working: https://ci.appveyor.com/project/mayn/packerlicious/build/1.0.13/job/eaisab8n3bpgr3rt
first failing: https://ci.appveyor.com/project/mayn/packerlicious/build/1.0.18/job/0vfv5twsesyorb2r

**Comment by shakeelmohamed** [comment]
Left a PR - #53.
Not sure why, but Travis CI was installing an older version of the cryptography package (somewhere in the dependency tree). In latest version of cryptography v2.1, Python 2.6 support has been deprecated - (see the [release notes](https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst#21---2017-10-11)).
