### ISSUE TITLE
version.py - single project version definition

### ISSUE THREAD

**Issue by mayn** [mayn/packerlicious#54]
### Actual Behavior
currently the packerlicious project version is defined in:
- https://github.com/mayn/packerlicious/blob/master/src/packerlicious/__init__.py#L22
- https://github.com/mayn/packerlicious/blob/master/setup.py#L21

this means during a release both locations need to be updated

### Expected Behavior
refactor to create a version.py file under `src/packerlicious` which contains the `__version__ = "0.4.0"` definition.

1.  `__init__.py` should be changed to import this new `version.py` and assign `__init__.py.__version__` to the value found in `version.py`
2. `setup.py` should open and read `src/packerlicious/version.py` and assign the version reference to the value found in `version.py`

**Comment by anurag-ks** [comment]
I am doing this

**Comment by Sidsharik** [comment]
have a look @mayn  PR submitted
