### ISSUE TITLE
setup.py - add classifiers

### ISSUE THREAD

**Issue by mayn** [mayn/packerlicious#55]
add the following project classifiers
- project license classification
- supported python version
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3 .6

see https://pypi.python.org/pypi?%3Aaction=list_classifiers for correct classifiers

**Comment by Sidsharik** [comment]
@mayn Can you explain a bit more I didnt get it. I would to contribute
