### ISSUE TITLE
install latest packer version as part of the setup for travis  / appveyor build environment

### ISSUE THREAD

**Issue by mayn** [mayn/packerlicious#63]
### Actual Behavior
functionality is being added that requires the presence of packer(https://packer.io) on our build system (see #27)

### Expected behavior
create an install.sh or equivalent (makefile?) for travisci and appveyor. This is to be used to install the latest packer installation.
In the future this may be expanded to test for compatibility across multiple packer versions.

**Comment by fuzzmz** [comment]
@mayn, do you want the latest binary release of Packer installed, or do you want it compiled from source?

**Comment by mayn** [comment]
@fuzzmz latest binary is fine. I want to ensure expected behavior from an integration test when using the python wrapper (#27)
