### ISSUE TITLE
builder/virtualbox-ovf add keep_registered

### ISSUE THREAD

**Issue by mayn** [mayn/packerlicious#70]
see https://www.packer.io/docs/builders/virtualbox-ovf.html#keep_registered

**Comment by fuzzmz** [comment]
I think this is already implemented [here](https://github.com/mayn/packerlicious/blob/master/src/packerlicious/builder.py#L1093).

**Comment by mayn** [comment]
@fuzzmz Apologize for the confusion, i provided the wrong doc link.. updated.
