### ISSUE TITLE
setup.py will not run with dot-slash

### ISSUE THREAD

**Issue by nrebhun** [mayn/packerlicious#82]
### packerlicious version
n/a

### Expected behavior
Setup script is runnable with `./`

### Actual behavior
`permission denied: ./setup.py`

### Steps to reproduce

From project root:
```sh
./setup.py
```

**Comment by mayn** [comment]
thanks for reporting, however this is intentional. common way to run setup.py is via `python setup.py`. 
closing, will revisit in future if needed.
